// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package root

import (
	"github.com/google/wire"
	"github.com/roger-king/go-chi-wire/pkg/config"
	"github.com/roger-king/go-chi-wire/pkg/handlers"
	"github.com/roger-king/go-chi-wire/pkg/server"
	"net/http"
)

// Injectors from app.go:

func InitializeApp() (*http.Server, error) {
	handler := handlers.NewRouter()
	configConfig := config.NewConfig()
	httpServer := server.CreateServer(handler, configConfig)
	return httpServer, nil
}

// app.go:

// GoChiWireSet - creates a wire set for the whole application.
var AppSet = wire.NewSet(server.ServerSet)
