// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package root

import (
	"github.com/google/wire"
	"github.com/roger-king/go-chi-wire/pkg/config"
	"github.com/roger-king/go-chi-wire/pkg/handlers"
	"github.com/roger-king/go-chi-wire/pkg/server"
	"net/http"
)

// Injectors from template.go:

func InitializeGoChiWire() (*http.Server, error) {
	handler := handlers.NewRouter()
	configConfig := config.NewConfig()
	httpServer := server.CreateServer(handler, configConfig)
	return httpServer, nil
}

// template.go:

// GoChiWireSet - creates a wire set for the whole application.
var GoChiWireSet = wire.NewSet(server.ServerSet)
